export function formatIssue(vendor, changes, classification) {
  const changeLines = changes
    .map((c) => `| \`${c.metric}\` | ${c.previous} | ${c.current} | ${c.delta} |`)
    .join('\n');

  const body = `## Risk Alert: ${vendor.vendor_name} (${vendor.vendor_domain})

${classification.summary}

### Score changes

| Metric | Previous | Current | Delta |
|---|---|---|---|
${changeLines}

### Recommended action

${classification.recommendation}

---
_Auto-generated by risk-alert-triage-bot from Fair TPRM vendor data._`;

  return {
    title: classification.title,
    body,
    labels: [`severity:${classification.severity}`, `category:${classification.category}`],
  };
}

export async function createIssue({ token, repo, title, body, labels }) {
  const response = await fetch(`https://api.github.com/repos/${repo}/issues`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ title, body, labels }),
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`GitHub issue creation failed (${response.status}): ${text}`);
  }

  return response.json();
}

export async function isIssueOpen({ token, repo, issueNumber }) {
  const response = await fetch(`https://api.github.com/repos/${repo}/issues/${issueNumber}`, {
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
    },
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch issue #${issueNumber} (${response.status})`);
  }

  const issue = await response.json();
  return issue.state === 'open';
}
