import type { Vendor, ScoreChange, Classification, Issue, CreatedIssue } from './types.js';

export function formatIssue(vendor: Vendor, changes: ScoreChange[], classification: Classification): Issue {
  const changeLines = changes
    .map((c) => `| \`${c.metric}\` | ${c.previous} | ${c.current} | ${c.delta} |`)
    .join('\n');

  const body = `## Risk Alert: ${vendor.vendor_name} (${vendor.vendor_domain})

${classification.summary}

### Score changes

| Metric | Previous | Current | Delta |
|---|---|---|---|
${changeLines}

### Recommended action

${classification.recommendation}

---
_Auto-generated by risk-alert-triage-bot from Fair TPRM vendor data._`;

  return {
    title: classification.title,
    body,
    labels: [`severity:${classification.severity}`, `category:${classification.category}`],
  };
}

export function formatInitialRiskIssue(vendor: Vendor, classification: Classification): Issue {
  const body = `## Baseline Risk Assessment: ${vendor.vendor_name} (${vendor.vendor_domain})

${classification.summary}

### Current scores

| Metric | Score |
|---|---|
| \`srs_score\` | ${vendor.current_srs_score} |
| \`shodan_score\` | ${vendor.current_shodan_score} |

### Recommended action

${classification.recommendation}

---
_Auto-generated by risk-alert-triage-bot from Fair TPRM vendor data._`;

  return {
    title: classification.title,
    body,
    labels: [`severity:${classification.severity}`, `category:${classification.category}`],
  };
}

export async function createIssue({ token, repo, title, body, labels }: { token: string; repo: string; title: string; body: string; labels: string[] }): Promise<CreatedIssue> {
  const response = await fetch(`https://api.github.com/repos/${repo}/issues`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ title, body, labels }),
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`GitHub issue creation failed (${response.status}): ${text}`);
  }

  return response.json();
}

export async function isIssueOpen({ token, repo, issueNumber }: { token: string; repo: string; issueNumber: number }): Promise<boolean> {
  const response = await fetch(`https://api.github.com/repos/${repo}/issues/${issueNumber}`, {
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
    },
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch issue #${issueNumber} (${response.status})`);
  }

  const issue = await response.json();
  return issue.state === 'open';
}
